---
title: "Figures_ch5"
output: github_document
---

## setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(bayesplot)
library(tidyverse)
library(ggplot2)
library(rstanarm)
library(rstan)
# enable multicore calculation
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r functions, include=FALSE}
# function for handling csv on web
get_data_from_url <- function(url) {
    readr::read_csv(RCurl::getURL(url))
}
```

## Model 5-3 重回帰
<!-- data preparation -->  
```{r model5-3_data, include = FALSE}
data_url1 <- "https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap05/input/data-attendance-1.txt"
stan_path <- "./stan/model5-3.stan"
d <- get_data_from_url(data_url1)
data <- list(N = nrow(d), A = d$A, Score = d$Score / 200, Y = d$Y)
```

```{r model5-3_output, message = FALSE}
fit <- stan(file = stan_path, data = data, seed = 1234)
ms <- rstan::extract(fit)
```

### Figure 5-2
```{r Figure5-2, echo = TRUE}
color_scheme_set("brightblue")
bayesplot::ppc_ribbon_grouped(y = d$Y, yrep = ms$y_pred, x = d$Score, group = d$A, facet_args = list(scales = "fixed", labeller = as_labeller(c("0" = "A=0", "1" = "A=1"))), prob_outer = 0.8, y_draw = "both") +
    panel_bg(fill = "gray90", color = NA) +
    grid_lines(color = "white") +
    labs(x = "Score", y = "Observed and Predicted y", title = "50% and 80% posterior predictive zone of Y vs Score")
```

### Figure 5-3
```{r Figure5-3, echo = TRUE}
color_scheme_set("purple")
bayesplot::ppc_intervals_grouped(y = d$Y, yrep = ms$y_pred, x = d$Y, group = d$A, facet_args = list(scales = "fixed", labeller = as_labeller(c("0" = "A=0", "1" = "A=1")))) +
    panel_bg(fill = "gray90", color = NA) +
    grid_lines(color = "white") +
    labs(x = "Observed y", y = "Predicted y", title = "50% and 80% posterior predictive interval of Y")
```

### Figure 5-4
`ms$noise`は`.stan`内の`generated quantities`として生成されているとする(Exercise5-2).
この`ms$noise`の最頻値を持つ`noise_df`を作ってプロットする.
```{r noise_df, echo = TRUE}
noise_df <- ms$noise %>%
    apply(2, function(x) {
        dens <- density(x)
        mode_x <- dens$x[which.max(dens$y)]
    }) %>%
    data.frame() %>%
    magrittr::set_colnames("err_mode") %>%
    mutate(A = d$A) # optional. used only in geom_qq
```
お手軽にプロットするならR base graphsが便利.
```{r plot_qqnorm, echo = TRUE}
qqnorm(noise_df$err_mode)
qqline(noise_df$err_mode, col = "red")
```

カテゴリ変数`A`でプロットを分けたいなら`ggplot`の`geom_qq_xxxx`を使う.
```{r plot_geom_qq, echo = TRUE}
noise_df %>%
    ggplot(mapping = aes(sample = err_mode, color = factor(A))) +
    geom_qq_line() +
    geom_qq() +
    guides(color = guide_legend("A")) +
    labs(title = "Normal QQ-plot of MAP error")
```

## Model 5-4 二項ロジスティック回帰
<!-- preparation -->  
```{r model5-4_data, include = FALSE}
data_url2 <- "https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap05/input/data-attendance-2.txt"
d <- get_data_from_url(data_url2)
stan_path <- "./stan/model5-4.stan"
data <- list(N = nrow(d), A = d$A, Score = d$Score / 200, M = d$M, Y = d$Y)
```

```{r model5-4_output, message = FALSE}
fit <- stan(file = stan_path, data = data, seed = 1234)
ms <- rstan::extract(fit)
```

### figure 5-8
```{r Figure5-8, echo = TRUE}
color_scheme_set("purple")
bayesplot::ppc_intervals_grouped(y = d$Y, yrep = ms$y_pred, x = d$Y, group = d$A, facet_args = list(scales = "fixed", labeller = as_labeller(c("0" = "A=0", "1" = "A=1")))) + panel_bg(fill = "gray90", color = NA) + grid_lines(color = "white") + labs(x = "Observed y", y = "Predicted y", title = "50% and 80% posterior predictive interval of Y")
```

## Model 5-5 ロジスティック回帰

### figure 5-10
```{r model5-5_data, include = FALSE}
data_url3 <- "https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap05/input/data-attendance-3.txt"
d <- get_data_from_url(data_url3)
stan_path <- "./stan/model5-5.stan"
cdn <- c(0, 0.2, 1)
names(cdn) <- c("A", "B", "C")
data <- list(N = nrow(d), A = d$A, Score = d$Score / 200, Weather = cdn[d$Weather], Y = d$Y)
```

```{r model5-5_output, message = FALSE}
fit <- stan(file = stan_path, data = data, seed = 1234)
ms <- rstan::extract(fit)
```

```{r figure5-10, echo = TRUE}
# process data for plot
data_plot <- bayesplot::ppc_scatter_avg_data(y = d$Y, yrep = ms$q, group = d$A) %>% transmute(A = group, y_obs = factor(y_obs), prob_pred = value)
# plot
data_plot %>%
    ggplot(aes(x = prob_pred, y = y_obs)) +
    facet_wrap(~A, ncol = 2, scales = "free_x", labeller = label_both) +
    geom_violin(trim = FALSE, size = 1, color = "grey80") +
    geom_point(aes(color = y_obs), position = position_jitter(w = 0, h = 0.2), size = 1, alpha = 0.5) +
    guides(color = "none") +
    labs(x = "Predicted Probability", y = "Y Observed", title = "Violin plot of Observed Y vs Predicted Probability")
```


## Model 5-6 ポアソン回帰
<!-- preparation -->  
```{r model5-6_data, include = FALSE}
d <- get_data_from_url(data_url2)
stan_path <- "./stan/model5-6.stan"
data <- list(N = nrow(d), A = d$A, Score = d$Score / 200, M = d$M)
```

```{r model5-6_output, message = FALSE}
fit <- stan(file = stan_path, data = data, seed = 1234)
ms <- rstan::extract(fit)
```

```{r draw_model5-6, echo = TRUE}
color_scheme_set("purple")
bayesplot::ppc_intervals_grouped(y = d$M, yrep = ms$m_pred, x = d$M, group = d$A, facet_args = list(scales = "fixed", labeller = as_labeller(c("0" = "A=0", "1" = "A=1")))) + panel_bg(fill = "gray90", color = NA) + grid_lines(color = "white") + labs(x = "Observed y", y = "Predicted y", title = "50% and 80% posterior predictive interval of Y")
```
